
extend type Query {
  bookMeta(id: String!): BookMetadata,
  bookMetas: [BookMetadata!]!,
}

extend type Mutation {
  createBookMeta(inp: CreateBookMetadataInp!): BookMetadata @isKind(kind: LIBRARY_STAFF),
  deleteBookMeta(id: String!): String @isKind(kind: LIBRARY_STAFF),
  updateBookMeta(inp: UpdateBookMetadataInp!): BookMetadata @isKind(kind: LIBRARY_STAFF),
}

type BookMetadata {
  id: String!,
  title: String!,
  isbn: String!,
  authors: [Author!]!,
  publicationID: String!,
  publication: Publication!,
  books: [Book!]!,
}

input CreateBookMetadataInp {
  id: String!,
  title: String!,
  isbn: String!,
  authorIDs: String!,
  publicationID: String!,
}

input UpdateBookMetadataInp {
  id: String!,
  title: String!,
  isbn: String!,
  authorIDs: String!,
  publicationID: String!,
}