
extend type Query {
  payment(id: String!): Payment,
  payments: [Payment!]!,
  userPayments(userID: String!): [Payment!]!,
}

extend type Mutation {
  resolvePayment(id: String!): Payment @isKind(kind: LIBRARY_STAFF),
}

type Payment {
  id: String!,
  userID: String!,
  user: User!,
  issueRecord: IssueRecord!,
  amount: Int!,
  resolved: Boolean!,
}

input CreatePaymentInp {
  id: String!,
  userID: String!,
  amount: Int!,
}