
extend type Query {
  user(id: String!): User,
  users: [User!]!,
}

extend type Mutation {
  createUser(inp: CreateUserInp!): User @isKind(kind: LIBRARY_STAFF),
  deleteUser(id: String!): String @isKind(kind: LIBRARY_STAFF),
  updateUser(inp: UpdateUserInp!): User,
}

type User {
  id: String!,
  kind: UserKind!,
  name: String!,
  email: String!,
  phone: String!,
  issueRecords: [IssueRecord!]!,
  payments: [Payment!]!,
}

enum UserKind {
  STUDENT,
  FACULTY,
  LIBRARY_STAFF,
}

input CreateUserInp {
  id: String!,
  kind: UserKind!,
  name: String!,
  email: String!,
  phone: String!,
  PasswordHash: String!,
}

input UpdateUserInp {
  id: String!,
  name: String,
  email: String,
  phone: String,
}