package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"

	"github.com/PICT-LibraryAutomation/granthpal/graph"
	"github.com/PICT-LibraryAutomation/granthpal/remote/models"
	"github.com/PICT-LibraryAutomation/granthpal/utils"
)

// Books is the resolver for the books field.
func (r *authorResolver) Books(ctx context.Context, obj *graph.Author) ([]*graph.BookMetadata, error) {
	var bs []models.BookMetadata
	if err := r.Remote.First(&models.Author{ID: obj.ID}).Association("Books").Find(&bs); err != nil {
		return nil, err
	}

	return utils.Map(bs, func(b models.BookMetadata) *graph.BookMetadata {
		return b.ToGraphQL()
	}), nil
}

// CreateAuthor is the resolver for the createAuthor field.
func (r *mutationResolver) CreateAuthor(ctx context.Context, inp graph.CreateAuthorInp) (*graph.Author, error) {
	panic(fmt.Errorf("not implemented: CreateAuthor - createAuthor"))
}

// DeleteAuthor is the resolver for the deleteAuthor field.
func (r *mutationResolver) DeleteAuthor(ctx context.Context, id string) (*string, error) {
	panic(fmt.Errorf("not implemented: DeleteAuthor - deleteAuthor"))
}

// UpdateAuthor is the resolver for the updateAuthor field.
func (r *mutationResolver) UpdateAuthor(ctx context.Context, inp graph.UpdateAuthorInp) (*graph.Author, error) {
	panic(fmt.Errorf("not implemented: UpdateAuthor - updateAuthor"))
}

// Author is the resolver for the author field.
func (r *queryResolver) Author(ctx context.Context, id string) (*graph.Author, error) {
	var a models.Author
	if err := r.Remote.First(&a, "id = ?", id).Error; err != nil {
		return nil, err
	}

	return a.ToGraphQL(), nil
}

// Authors is the resolver for the authors field.
func (r *queryResolver) Authors(ctx context.Context) ([]*graph.Author, error) {
	var as []models.Author
	if err := r.Remote.Find(&as).Error; err != nil {
		return nil, err
	}

	return utils.Map(as, func(a models.Author) *graph.Author {
		return a.ToGraphQL()
	}), nil
}

// Author returns graph.AuthorResolver implementation.
func (r *Resolver) Author() graph.AuthorResolver { return &authorResolver{r} }

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type authorResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
