package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"

	"github.com/PICT-LibraryAutomation/granthpal/graph"
)

// Meta is the resolver for the meta field.
func (r *bookResolver) Meta(ctx context.Context, obj *graph.Book) (*graph.BookMetadata, error) {
	panic(fmt.Errorf("not implemented: Meta - meta"))
}

// IssueRecords is the resolver for the issueRecords field.
func (r *bookResolver) IssueRecords(ctx context.Context, obj *graph.Book) ([]*graph.IssueRecord, error) {
	panic(fmt.Errorf("not implemented: IssueRecords - issueRecords"))
}

// CreateBook is the resolver for the createBook field.
func (r *mutationResolver) CreateBook(ctx context.Context, inp graph.CreateBookInp) (*graph.Book, error) {
	panic(fmt.Errorf("not implemented: CreateBook - createBook"))
}

// RemoveBook is the resolver for the removeBook field.
func (r *mutationResolver) RemoveBook(ctx context.Context, id string) (*string, error) {
	panic(fmt.Errorf("not implemented: RemoveBook - removeBook"))
}

// UpdateBook is the resolver for the updateBook field.
func (r *mutationResolver) UpdateBook(ctx context.Context, inp graph.UpdateBookInp) (*graph.Book, error) {
	panic(fmt.Errorf("not implemented: UpdateBook - updateBook"))
}

// Book is the resolver for the book field.
func (r *queryResolver) Book(ctx context.Context, id string) (*graph.Book, error) {
	panic(fmt.Errorf("not implemented: Book - book"))
}

// Books is the resolver for the books field.
func (r *queryResolver) Books(ctx context.Context) ([]*graph.Book, error) {
	panic(fmt.Errorf("not implemented: Books - books"))
}

// Book returns graph.BookResolver implementation.
func (r *Resolver) Book() graph.BookResolver { return &bookResolver{r} }

type bookResolver struct{ *Resolver }
