package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"

	"github.com/PICT-LibraryAutomation/granthpal/graph"
	"github.com/PICT-LibraryAutomation/granthpal/remote/models"
	"github.com/PICT-LibraryAutomation/granthpal/utils"
)

// User is the resolver for the user field.
func (r *issueRecordResolver) User(ctx context.Context, obj *graph.IssueRecord) (*graph.User, error) {
	var u models.User
	if err := r.Remote.First(&u, "id = ?", obj.UserID).Error; err != nil {
		return nil, err
	}

	return u.ToGraphQL(), nil
}

// Book is the resolver for the book field.
func (r *issueRecordResolver) Book(ctx context.Context, obj *graph.IssueRecord) (*graph.Book, error) {
	var b models.Book
	if err := r.Remote.First(&b, "id = ?", obj.BookID).Error; err != nil {
		return nil, err
	}

	return b.ToGraphQL(), nil
}

// Payment is the resolver for the payment field.
func (r *issueRecordResolver) Payment(ctx context.Context, obj *graph.IssueRecord) (*graph.Payment, error) {
	var p models.Payment
	if obj.PaymentID == nil {
		return nil, nil
	}

	if err := r.Remote.First(&p, "id = ?", *obj.PaymentID).Error; err != nil {
		return nil, err
	}

	return p.ToGraphQL(), nil
}

// IssueBook is the resolver for the issueBook field.
func (r *mutationResolver) IssueBook(ctx context.Context, inp graph.IssueBookInp) (*graph.IssueRecord, error) {
	panic(fmt.Errorf("not implemented: IssueBook - issueBook"))
}

// ReturnBook is the resolver for the returnBook field.
func (r *mutationResolver) ReturnBook(ctx context.Context, bookID string) (*graph.IssueRecord, error) {
	panic(fmt.Errorf("not implemented: ReturnBook - returnBook"))
}

// RenewBook is the resolver for the renewBook field.
func (r *mutationResolver) RenewBook(ctx context.Context, bookID string) (*graph.IssueRecord, error) {
	panic(fmt.Errorf("not implemented: RenewBook - renewBook"))
}

// IssueRecord is the resolver for the issueRecord field.
func (r *queryResolver) IssueRecord(ctx context.Context, id string) (*graph.IssueRecord, error) {
	var ir models.IssueRecord
	if err := r.Remote.First(&ir, "id = ?", id).Error; err != nil {
		return nil, err
	}

	return ir.ToGraphQL(), nil
}

// IssueRecords is the resolver for the issueRecords field.
func (r *queryResolver) IssueRecords(ctx context.Context) ([]*graph.IssueRecord, error) {
	var irs []models.IssueRecord
	if err := r.Remote.Find(&irs).Error; err != nil {
		return nil, err
	}

	return utils.Map(irs, func(ir models.IssueRecord) *graph.IssueRecord {
		return ir.ToGraphQL()
	}), nil
}

// IssueRecord returns graph.IssueRecordResolver implementation.
func (r *Resolver) IssueRecord() graph.IssueRecordResolver { return &issueRecordResolver{r} }

type issueRecordResolver struct{ *Resolver }
