package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"
	"time"

	"github.com/PICT-LibraryAutomation/granthpal/graph"
	"github.com/PICT-LibraryAutomation/granthpal/remote/models"
	"github.com/PICT-LibraryAutomation/granthpal/utils"
	"github.com/google/uuid"
)

// User is the resolver for the user field.
func (r *issueRecordResolver) User(ctx context.Context, obj *graph.IssueRecord) (*graph.User, error) {
	var u models.User
	if err := r.Remote.First(&u, "id = ?", obj.UserID).Error; err != nil {
		return nil, err
	}

	return u.ToGraphQL(), nil
}

// Book is the resolver for the book field.
func (r *issueRecordResolver) Book(ctx context.Context, obj *graph.IssueRecord) (*graph.Book, error) {
	var b models.Book
	if err := r.Remote.First(&b, "id = ?", obj.BookID).Error; err != nil {
		return nil, err
	}

	return b.ToGraphQL(), nil
}

// Payment is the resolver for the payment field.
func (r *issueRecordResolver) Payment(ctx context.Context, obj *graph.IssueRecord) (*graph.Payment, error) {
	var p models.Payment
	if obj.PaymentID == nil {
		return nil, nil
	}

	if err := r.Remote.First(&p, "id = ?", *obj.PaymentID).Error; err != nil {
		return nil, err
	}

	return p.ToGraphQL(), nil
}

// IssueBook is the resolver for the issueBook field.
func (r *mutationResolver) IssueBook(ctx context.Context, inp graph.IssueBookInp) (*graph.IssueRecord, error) {
	ir := models.IssueRecord{
		ID:         uuid.NewString(),
		UserID:     inp.UserID,
		BookID:     inp.BookID,
		PaymentID:  nil,
		IssueDate:  time.Now().Local(),
		ReturnDate: time.Now().Add(utils.ISSUE_PERIOD).Local(),
		Returned:   false,
	}

	if err := r.Remote.Save(&ir).Error; err != nil {
		return nil, err
	}

	return ir.ToGraphQL(), nil
}

// ReturnBook is the resolver for the returnBook field.
func (r *mutationResolver) ReturnBook(ctx context.Context, bookID string) (*graph.IssueRecord, error) {
	var ir models.IssueRecord
	if err := r.Remote.First(&ir, "book_id = ?", bookID).Error; err != nil {
		return nil, err
	}

	if ir.ReturnDate.Local().After(time.Now().Local()) {
		days := ir.ReturnDate.Local().Sub(time.Now().Local()).Hours() / 24
		amount := utils.LATE_FEE_PER_DAY * days

		if ir.PaymentID == nil {
			p := models.Payment{
				ID:       uuid.NewString(),
				UserID:   ir.UserID,
				Amount:   int(amount),
				Resolved: false,
			}

			if err := r.Remote.Save(&p).Error; err != nil {
				return nil, err
			}

			ir.PaymentID = &p.ID
		} else {
			var p models.Payment
			if err := r.Remote.First(&p, "id = ?", *ir.PaymentID).Error; err != nil {
				return nil, err
			}

			if p.Resolved {
				p.Resolved = false
				p.Amount = int(amount)

			} else {
				p.Amount += int(amount)
			}

			if err := r.Remote.Save(&p).Error; err != nil {
				return nil, err
			}
		}
	}

	ir.Returned = true
	if err := r.Remote.Save(&ir).Error; err != nil {
		return nil, err
	}

	return ir.ToGraphQL(), nil
}

// RenewBook is the resolver for the renewBook field.
func (r *mutationResolver) RenewBook(ctx context.Context, bookID string) (*graph.IssueRecord, error) {
	var ir models.IssueRecord
	if err := r.Remote.First(&ir, "book_id = ?", bookID).Error; err != nil {
		return nil, err
	}

	if ir.Returned {
		return nil, fmt.Errorf("book has already been returned")
	}

	if ir.ReturnDate.Local().After(time.Now().Local()) {
		days := ir.ReturnDate.Local().Sub(time.Now().Local()).Hours() / 24
		amount := utils.LATE_FEE_PER_DAY * days

		if ir.PaymentID == nil {
			p := models.Payment{
				ID:       uuid.NewString(),
				UserID:   ir.UserID,
				Amount:   int(amount),
				Resolved: false,
			}

			if err := r.Remote.Save(&p).Error; err != nil {
				return nil, err
			}

			ir.PaymentID = &p.ID
		} else {
			var p models.Payment
			if err := r.Remote.First(&p, "id = ?", *ir.PaymentID).Error; err != nil {
				return nil, err
			}

			if p.Resolved {
				p.Resolved = false
				p.Amount = int(amount)

			} else {
				p.Amount += int(amount)
			}

			if err := r.Remote.Save(&p).Error; err != nil {
				return nil, err
			}
		}
	}

	ir.ReturnDate = time.Now().Add(utils.ISSUE_PERIOD).Local()
	if err := r.Remote.Save(&ir).Error; err != nil {
		return nil, err
	}

	return ir.ToGraphQL(), nil
}

// IssueRecord is the resolver for the issueRecord field.
func (r *queryResolver) IssueRecord(ctx context.Context, id string) (*graph.IssueRecord, error) {
	var ir models.IssueRecord
	if err := r.Remote.First(&ir, "id = ?", id).Error; err != nil {
		return nil, err
	}

	return ir.ToGraphQL(), nil
}

// IssueRecords is the resolver for the issueRecords field.
func (r *queryResolver) IssueRecords(ctx context.Context) ([]*graph.IssueRecord, error) {
	var irs []models.IssueRecord
	if err := r.Remote.Find(&irs).Error; err != nil {
		return nil, err
	}

	return utils.Map(irs, func(ir models.IssueRecord) *graph.IssueRecord {
		return ir.ToGraphQL()
	}), nil
}

// IssueRecord returns graph.IssueRecordResolver implementation.
func (r *Resolver) IssueRecord() graph.IssueRecordResolver { return &issueRecordResolver{r} }

type issueRecordResolver struct{ *Resolver }
